// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(4)]
    [uFrame.Attributes.uFrameIdentifier("3c039200-a3a9-414c-9733-1edcb1a3ca68")]
    public partial class bullet : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 4;
            }
        }
    }
}
