// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(5)]
    [uFrame.Attributes.uFrameIdentifier("9cae9d5e-4fe7-48fa-bfcf-e214242c1f34")]
    public partial class Player : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 5;
            }
        }
    }
}
