// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(3)]
    [uFrame.Attributes.uFrameIdentifier("4d1272cc-68a5-46fc-8dce-4f293675718f")]
    public partial class WandRight : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 3;
            }
        }
    }
}
