// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    using ViveDatabase;
    
    
    [uFrame.Attributes.ComponentId(1)]
    [uFrame.Attributes.uFrameIdentifier("dad9c878-7c47-4304-8f08-a3f8eb62bea5")]
    public partial class Wands : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private GameObject _bullet;
        
        [UnityEngine.SerializeField()]
        private WandRight _Right;
        
        [UnityEngine.SerializeField()]
        private WandLeft _Left;
        
        private Subject<PropertyChangedEvent<GameObject>> _bulletObservable;
        
        private PropertyChangedEvent<GameObject> _bulletEvent;
        
        private Subject<PropertyChangedEvent<WandRight>> _RightObservable;
        
        private PropertyChangedEvent<WandRight> _RightEvent;
        
        private Subject<PropertyChangedEvent<WandLeft>> _LeftObservable;
        
        private PropertyChangedEvent<WandLeft> _LeftEvent;
        
        public override int ComponentId {
            get {
                return 1;
            }
        }
        
        public IObservable<PropertyChangedEvent<GameObject>> bulletObservable {
            get {
                return _bulletObservable ?? (_bulletObservable = new Subject<PropertyChangedEvent<GameObject>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<WandRight>> RightObservable {
            get {
                return _RightObservable ?? (_RightObservable = new Subject<PropertyChangedEvent<WandRight>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<WandLeft>> LeftObservable {
            get {
                return _LeftObservable ?? (_LeftObservable = new Subject<PropertyChangedEvent<WandLeft>>());
            }
        }
        
        public GameObject bullet {
            get {
                return _bullet;
            }
            set {
                Setbullet(value);
            }
        }
        
        public WandRight Right {
            get {
                return _Right;
            }
            set {
                SetRight(value);
            }
        }
        
        public WandLeft Left {
            get {
                return _Left;
            }
            set {
                SetLeft(value);
            }
        }
        
        public virtual void Setbullet(GameObject value) {
            SetProperty(ref _bullet, value, ref _bulletEvent, _bulletObservable);
        }
        
        public virtual void SetRight(WandRight value) {
            SetProperty(ref _Right, value, ref _RightEvent, _RightObservable);
        }
        
        public virtual void SetLeft(WandLeft value) {
            SetProperty(ref _Left, value, ref _LeftEvent, _LeftObservable);
        }
    }
}
