// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(8)]
    [uFrame.Attributes.uFrameIdentifier("86712a6a-37da-49da-b9d7-7c4440514be8")]
    public partial class Weapon : uFrame.ECS.Components.EcsComponent {
        
        public override int ComponentId {
            get {
                return 8;
            }
        }
    }
}
