// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    using ViveDatabase;
    
    
    public partial class EnemySystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<Wands> _WandsManager;
        
        private IEcsComponentManagerOf<Menu> _MenuManager;
        
        private IEcsComponentManagerOf<WandLeft> _WandLeftManager;
        
        private IEcsComponentManagerOf<EnemySpawner> _EnemySpawnerManager;
        
        private IEcsComponentManagerOf<bullet> _bulletManager;
        
        private IEcsComponentManagerOf<Enemy> _EnemyManager;
        
        private IEcsComponentManagerOf<Weapon> _WeaponManager;
        
        private IEcsComponentManagerOf<WandRight> _WandRightManager;
        
        private IEcsComponentManagerOf<Player> _PlayerManager;
        
        public IEcsComponentManagerOf<Wands> WandsManager {
            get {
                return _WandsManager;
            }
            set {
                _WandsManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Menu> MenuManager {
            get {
                return _MenuManager;
            }
            set {
                _MenuManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandLeft> WandLeftManager {
            get {
                return _WandLeftManager;
            }
            set {
                _WandLeftManager = value;
            }
        }
        
        public IEcsComponentManagerOf<EnemySpawner> EnemySpawnerManager {
            get {
                return _EnemySpawnerManager;
            }
            set {
                _EnemySpawnerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<bullet> bulletManager {
            get {
                return _bulletManager;
            }
            set {
                _bulletManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Enemy> EnemyManager {
            get {
                return _EnemyManager;
            }
            set {
                _EnemyManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Weapon> WeaponManager {
            get {
                return _WeaponManager;
            }
            set {
                _WeaponManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandRight> WandRightManager {
            get {
                return _WandRightManager;
            }
            set {
                _WandRightManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Player> PlayerManager {
            get {
                return _PlayerManager;
            }
            set {
                _PlayerManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            WandsManager = ComponentSystem.RegisterComponent<Wands>(1);
            MenuManager = ComponentSystem.RegisterComponent<Menu>(7);
            WandLeftManager = ComponentSystem.RegisterComponent<WandLeft>(2);
            EnemySpawnerManager = ComponentSystem.RegisterComponent<EnemySpawner>(9);
            bulletManager = ComponentSystem.RegisterComponent<bullet>(4);
            EnemyManager = ComponentSystem.RegisterComponent<Enemy>(10);
            WeaponManager = ComponentSystem.RegisterComponent<Weapon>(8);
            WandRightManager = ComponentSystem.RegisterComponent<WandRight>(3);
            PlayerManager = ComponentSystem.RegisterComponent<Player>(5);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("2842d715-1bcf-46a9-924f-a9ada97b9594")]
    public partial class EnemySystem : EnemySystemBase {
        
        private static EnemySystem _Instance;
        
        public EnemySystem() {
            Instance = this;
        }
        
        public static EnemySystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
