// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ViveDatabase {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    using ViveDatabase;
    
    
    public partial class InputSystemBase : uFrame.ECS.Systems.EcsSystem, uFrame.ECS.APIs.ISystemUpdate {
        
        private IEcsComponentManagerOf<Wands> _WandsManager;
        
        private IEcsComponentManagerOf<Menu> _MenuManager;
        
        private IEcsComponentManagerOf<WandLeft> _WandLeftManager;
        
        private IEcsComponentManagerOf<bullet> _bulletManager;
        
        private IEcsComponentManagerOf<WandRight> _WandRightManager;
        
        private IEcsComponentManagerOf<Player> _PlayerManager;
        
        public IEcsComponentManagerOf<Wands> WandsManager {
            get {
                return _WandsManager;
            }
            set {
                _WandsManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Menu> MenuManager {
            get {
                return _MenuManager;
            }
            set {
                _MenuManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandLeft> WandLeftManager {
            get {
                return _WandLeftManager;
            }
            set {
                _WandLeftManager = value;
            }
        }
        
        public IEcsComponentManagerOf<bullet> bulletManager {
            get {
                return _bulletManager;
            }
            set {
                _bulletManager = value;
            }
        }
        
        public IEcsComponentManagerOf<WandRight> WandRightManager {
            get {
                return _WandRightManager;
            }
            set {
                _WandRightManager = value;
            }
        }
        
        public IEcsComponentManagerOf<Player> PlayerManager {
            get {
                return _PlayerManager;
            }
            set {
                _PlayerManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            WandsManager = ComponentSystem.RegisterComponent<Wands>(1);
            MenuManager = ComponentSystem.RegisterComponent<Menu>(7);
            WandLeftManager = ComponentSystem.RegisterComponent<WandLeft>(2);
            bulletManager = ComponentSystem.RegisterComponent<bullet>(4);
            WandRightManager = ComponentSystem.RegisterComponent<WandRight>(3);
            PlayerManager = ComponentSystem.RegisterComponent<Player>(5);
            this.OnEvent<uFrame.Kernel.KernelLoadedEvent>().Subscribe(_=>{ InputSystemKernelLoadedFilter(_); }).DisposeWith(this);
            this.OnEvent<ViveDatabase.ShootEvent>().Subscribe(_=>{ InputSystemShootEventFilter(_); }).DisposeWith(this);
            this.OnEvent<ViveDatabase.TeleportEvent>().Subscribe(_=>{ InputSystemTeleportEventFilter(_); }).DisposeWith(this);
            this.OnEvent<ViveDatabase.MenuEvent>().Subscribe(_=>{ InputSystemMenuEventFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher>().Subscribe(_=>{ InputSystemOnTriggerEnterFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void InputSystemKernelLoadedHandler(uFrame.Kernel.KernelLoadedEvent data, Wands group) {
        }
        
        protected void InputSystemKernelLoadedFilter(uFrame.Kernel.KernelLoadedEvent data) {
            var WandsItems = WandsManager.Components;
            for (var WandsIndex = 0
            ; WandsIndex < WandsItems.Count; WandsIndex++
            ) {
                if (!WandsItems[WandsIndex].Enabled) {
                    continue;
                }
                this.InputSystemKernelLoadedHandler(data, WandsItems[WandsIndex]);
            }
        }
        
        protected virtual void InputSystemUpdateHandler(Wands group) {
        }
        
        protected void InputSystemUpdateFilter() {
            var WandsItems = WandsManager.Components;
            for (var WandsIndex = 0
            ; WandsIndex < WandsItems.Count; WandsIndex++
            ) {
                if (!WandsItems[WandsIndex].Enabled) {
                    continue;
                }
                this.InputSystemUpdateHandler(WandsItems[WandsIndex]);
            }
        }
        
        public virtual void SystemUpdate() {
            InputSystemUpdateFilter();
        }
        
        protected virtual void InputSystemShootEventHandler(ViveDatabase.ShootEvent data, Wands group) {
        }
        
        protected void InputSystemShootEventFilter(ViveDatabase.ShootEvent data) {
            var WandsItems = WandsManager.Components;
            for (var WandsIndex = 0
            ; WandsIndex < WandsItems.Count; WandsIndex++
            ) {
                if (!WandsItems[WandsIndex].Enabled) {
                    continue;
                }
                this.InputSystemShootEventHandler(data, WandsItems[WandsIndex]);
            }
        }
        
        protected virtual void InputSystemTeleportEventHandler(ViveDatabase.TeleportEvent data, Wands group) {
        }
        
        protected void InputSystemTeleportEventFilter(ViveDatabase.TeleportEvent data) {
            var WandsItems = WandsManager.Components;
            for (var WandsIndex = 0
            ; WandsIndex < WandsItems.Count; WandsIndex++
            ) {
                if (!WandsItems[WandsIndex].Enabled) {
                    continue;
                }
                this.InputSystemTeleportEventHandler(data, WandsItems[WandsIndex]);
            }
        }
        
        protected virtual void InputSystemMenuEventHandler(ViveDatabase.MenuEvent data, Wands group) {
        }
        
        protected void InputSystemMenuEventFilter(ViveDatabase.MenuEvent data) {
            var WandsItems = WandsManager.Components;
            for (var WandsIndex = 0
            ; WandsIndex < WandsItems.Count; WandsIndex++
            ) {
                if (!WandsItems[WandsIndex].Enabled) {
                    continue;
                }
                this.InputSystemMenuEventHandler(data, WandsItems[WandsIndex]);
            }
        }
        
        protected virtual void InputSystemOnTriggerEnterHandler(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data, Menu collider, WandLeft source) {
        }
        
        protected void InputSystemOnTriggerEnterFilter(uFrame.ECS.UnityUtilities.OnTriggerEnterDispatcher data) {
            var ColliderMenu = MenuManager[data.ColliderId];
            if (ColliderMenu == null) {
                return;
            }
            if (!ColliderMenu.Enabled) {
                return;
            }
            var SourceWandLeft = WandLeftManager[data.EntityId];
            if (SourceWandLeft == null) {
                return;
            }
            if (!SourceWandLeft.Enabled) {
                return;
            }
            this.InputSystemOnTriggerEnterHandler(data, ColliderMenu, SourceWandLeft);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("78c0d850-4d4f-4de4-a31f-55c314216749")]
    public partial class InputSystem : InputSystemBase {
        
        private static InputSystem _Instance;
        
        public InputSystem() {
            Instance = this;
        }
        
        public static InputSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
